name: Backend Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
  

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm i
      
    - name: Run tests
      working-directory: ./backend
      run: npm test
